export type Surah = {
  n: number; // mushaf number
  en: string;
  ar: string;
  verses: number;
  type: "meccan" | "medinan";
  nuzul: number; // chronological order
};

export const SURAHS: Surah[] = [
  { n: 1, en: "Al-Fatiha", ar: "الفاتحة", verses: 7, type: "meccan", nuzul: 5 },
  { n: 2, en: "Al-Baqarah", ar: "البقرة", verses: 286, type: "medinan", nuzul: 87 },
  { n: 3, en: "Al-Imran", ar: "آل عمران", verses: 200, type: "medinan", nuzul: 89 },
  { n: 4, en: "An-Nisa", ar: "النساء", verses: 176, type: "medinan", nuzul: 92 },
  { n: 5, en: "Al-Maidah", ar: "المائدة", verses: 120, type: "medinan", nuzul: 112 },
  { n: 6, en: "Al-Anam", ar: "الأنعام", verses: 165, type: "meccan", nuzul: 55 },
  { n: 7, en: "Al-Araf", ar: "الأعراف", verses: 206, type: "meccan", nuzul: 39 },
  { n: 8, en: "Al-Anfal", ar: "الأنفال", verses: 75, type: "medinan", nuzul: 88 },
  { n: 9, en: "At-Tawbah", ar: "التوبة", verses: 129, type: "medinan", nuzul: 113 },
  { n: 10, en: "Yunus", ar: "يونس", verses: 109, type: "meccan", nuzul: 51 },
  { n: 11, en: "Hud", ar: "هود", verses: 123, type: "meccan", nuzul: 52 },
  { n: 12, en: "Yusuf", ar: "يوسف", verses: 111, type: "meccan", nuzul: 53 },
  { n: 13, en: "Ar-Rad", ar: "الرعد", verses: 43, type: "medinan", nuzul: 96 },
  { n: 14, en: "Ibrahim", ar: "إبراهيم", verses: 52, type: "meccan", nuzul: 72 },
  { n: 15, en: "Al-Hijr", ar: "الحجر", verses: 99, type: "meccan", nuzul: 54 },
  { n: 16, en: "An-Nahl", ar: "النحل", verses: 128, type: "meccan", nuzul: 70 },
  { n: 17, en: "Al-Isra", ar: "الإسراء", verses: 111, type: "meccan", nuzul: 50 },
  { n: 18, en: "Al-Kahf", ar: "الكهف", verses: 110, type: "meccan", nuzul: 69 },
  { n: 19, en: "Maryam", ar: "مريم", verses: 98, type: "meccan", nuzul: 44 },
  { n: 20, en: "Ta-Ha", ar: "طه", verses: 135, type: "meccan", nuzul: 45 },
  { n: 21, en: "Al-Anbiya", ar: "الأنبياء", verses: 112, type: "meccan", nuzul: 73 },
  { n: 22, en: "Al-Hajj", ar: "الحج", verses: 78, type: "medinan", nuzul: 103 },
  { n: 23, en: "Al-Muminun", ar: "المؤمنون", verses: 118, type: "meccan", nuzul: 74 },
  { n: 24, en: "An-Nur", ar: "النور", verses: 64, type: "medinan", nuzul: 102 },
  { n: 25, en: "Al-Furqan", ar: "الفرقان", verses: 77, type: "meccan", nuzul: 42 },
  { n: 26, en: "Ash-Shuara", ar: "الشعراء", verses: 227, type: "meccan", nuzul: 47 },
  { n: 27, en: "An-Naml", ar: "النمل", verses: 93, type: "meccan", nuzul: 48 },
  { n: 28, en: "Al-Qasas", ar: "القصص", verses: 88, type: "meccan", nuzul: 49 },
  { n: 29, en: "Al-Ankabut", ar: "العنكبوت", verses: 69, type: "meccan", nuzul: 85 },
  { n: 30, en: "Ar-Rum", ar: "الروم", verses: 60, type: "meccan", nuzul: 84 },
  { n: 31, en: "Luqman", ar: "لقمان", verses: 34, type: "meccan", nuzul: 57 },
  { n: 32, en: "As-Sajda", ar: "السجدة", verses: 30, type: "meccan", nuzul: 75 },
  { n: 33, en: "Al-Ahzab", ar: "الأحزاب", verses: 73, type: "medinan", nuzul: 90 },
  { n: 34, en: "Saba", ar: "سبأ", verses: 54, type: "meccan", nuzul: 58 },
  { n: 35, en: "Fatir", ar: "فاطر", verses: 45, type: "meccan", nuzul: 43 },
  { n: 36, en: "Ya-Sin", ar: "يس", verses: 83, type: "meccan", nuzul: 41 },
  { n: 37, en: "As-Saffat", ar: "الصافات", verses: 182, type: "meccan", nuzul: 56 },
  { n: 38, en: "Sad", ar: "ص", verses: 88, type: "meccan", nuzul: 38 },
  { n: 39, en: "Az-Zumar", ar: "الزمر", verses: 75, type: "meccan", nuzul: 59 },
  { n: 40, en: "Ghafir", ar: "غافر", verses: 85, type: "meccan", nuzul: 60 },
  { n: 41, en: "Fussilat", ar: "فصلت", verses: 54, type: "meccan", nuzul: 61 },
  { n: 42, en: "Ash-Shura", ar: "الشورى", verses: 53, type: "meccan", nuzul: 62 },
  { n: 43, en: "Az-Zukhruf", ar: "الزخرف", verses: 89, type: "meccan", nuzul: 63 },
  { n: 44, en: "Ad-Dukhan", ar: "الدخان", verses: 59, type: "meccan", nuzul: 64 },
  { n: 45, en: "Al-Jathiya", ar: "الجاثية", verses: 37, type: "meccan", nuzul: 65 },
  { n: 46, en: "Al-Ahqaf", ar: "الأحقاف", verses: 35, type: "meccan", nuzul: 66 },
  { n: 47, en: "Muhammad", ar: "محمد", verses: 38, type: "medinan", nuzul: 95 },
  { n: 48, en: "Al-Fath", ar: "الفتح", verses: 29, type: "medinan", nuzul: 111 },
  { n: 49, en: "Al-Hujurat", ar: "الحجرات", verses: 18, type: "medinan", nuzul: 106 },
  { n: 50, en: "Qaf", ar: "ق", verses: 45, type: "meccan", nuzul: 34 },
  { n: 51, en: "Adh-Dhariyat", ar: "الذاريات", verses: 60, type: "meccan", nuzul: 67 },
  { n: 52, en: "At-Tur", ar: "الطور", verses: 49, type: "meccan", nuzul: 76 },
  { n: 53, en: "An-Najm", ar: "النجم", verses: 62, type: "meccan", nuzul: 23 },
  { n: 54, en: "Al-Qamar", ar: "القمر", verses: 55, type: "meccan", nuzul: 37 },
  { n: 55, en: "Ar-Rahman", ar: "الرحمن", verses: 78, type: "meccan", nuzul: 97 },
  { n: 56, en: "Al-Waqiah", ar: "الواقعة", verses: 96, type: "meccan", nuzul: 46 },
  { n: 57, en: "Al-Hadid", ar: "الحديد", verses: 29, type: "medinan", nuzul: 94 },
  { n: 58, en: "Al-Mujadila", ar: "المجادلة", verses: 22, type: "medinan", nuzul: 105 },
  { n: 59, en: "Al-Hashr", ar: "الحشر", verses: 24, type: "medinan", nuzul: 101 },
  { n: 60, en: "Al-Mumtahina", ar: "الممتحنة", verses: 13, type: "medinan", nuzul: 91 },
  { n: 61, en: "As-Saff", ar: "الصف", verses: 14, type: "medinan", nuzul: 109 },
  { n: 62, en: "Al-Jumuah", ar: "الجمعة", verses: 11, type: "medinan", nuzul: 110 },
  { n: 63, en: "Al-Munafiqun", ar: "المنافقون", verses: 11, type: "medinan", nuzul: 104 },
  { n: 64, en: "At-Taghabun", ar: "التغابن", verses: 18, type: "medinan", nuzul: 108 },
  { n: 65, en: "At-Talaq", ar: "الطلاق", verses: 12, type: "medinan", nuzul: 99 },
  { n: 66, en: "At-Tahrim", ar: "التحريم", verses: 12, type: "medinan", nuzul: 107 },
  { n: 67, en: "Al-Mulk", ar: "الملك", verses: 30, type: "meccan", nuzul: 77 },
  { n: 68, en: "Al-Qalam", ar: "القلم", verses: 52, type: "meccan", nuzul: 2 },
  { n: 69, en: "Al-Haqqah", ar: "الحاقة", verses: 52, type: "meccan", nuzul: 78 },
  { n: 70, en: "Al-Maarij", ar: "المعارج", verses: 44, type: "meccan", nuzul: 79 },
  { n: 71, en: "Nuh", ar: "نوح", verses: 28, type: "meccan", nuzul: 71 },
  { n: 72, en: "Al-Jinn", ar: "الجن", verses: 28, type: "meccan", nuzul: 40 },
  { n: 73, en: "Al-Muzzammil", ar: "المزمل", verses: 20, type: "meccan", nuzul: 3 },
  { n: 74, en: "Al-Muddaththir", ar: "المدثر", verses: 56, type: "meccan", nuzul: 4 },
  { n: 75, en: "Al-Qiyamah", ar: "القيامة", verses: 40, type: "meccan", nuzul: 31 },
  { n: 76, en: "Al-Insan", ar: "الإنسان", verses: 31, type: "medinan", nuzul: 98 },
  { n: 77, en: "Al-Mursalat", ar: "المرسلات", verses: 50, type: "meccan", nuzul: 33 },
  { n: 78, en: "An-Naba", ar: "النبأ", verses: 40, type: "meccan", nuzul: 80 },
  { n: 79, en: "An-Naziat", ar: "النازعات", verses: 46, type: "meccan", nuzul: 81 },
  { n: 80, en: "Abasa", ar: "عبس", verses: 42, type: "meccan", nuzul: 24 },
  { n: 81, en: "At-Takwir", ar: "التكوير", verses: 29, type: "meccan", nuzul: 7 },
  { n: 82, en: "Al-Infitar", ar: "الانفطار", verses: 19, type: "meccan", nuzul: 82 },
  { n: 83, en: "Al-Mutaffifin", ar: "المطففين", verses: 36, type: "meccan", nuzul: 86 },
  { n: 84, en: "Al-Inshiqaq", ar: "الانشقاق", verses: 25, type: "meccan", nuzul: 83 },
  { n: 85, en: "Al-Buruj", ar: "البروج", verses: 22, type: "meccan", nuzul: 27 },
  { n: 86, en: "At-Tariq", ar: "الطارق", verses: 17, type: "meccan", nuzul: 36 },
  { n: 87, en: "Al-Ala", ar: "الأعلى", verses: 19, type: "meccan", nuzul: 8 },
  { n: 88, en: "Al-Ghashiyah", ar: "الغاشية", verses: 26, type: "meccan", nuzul: 68 },
  { n: 89, en: "Al-Fajr", ar: "الفجر", verses: 30, type: "meccan", nuzul: 10 },
  { n: 90, en: "Al-Balad", ar: "البلد", verses: 20, type: "meccan", nuzul: 35 },
  { n: 91, en: "Ash-Shams", ar: "الشمس", verses: 15, type: "meccan", nuzul: 26 },
  { n: 92, en: "Al-Layl", ar: "الليل", verses: 21, type: "meccan", nuzul: 9 },
  { n: 93, en: "Ad-Duha", ar: "الضحى", verses: 11, type: "meccan", nuzul: 11 },
  { n: 94, en: "Ash-Sharh", ar: "الشرح", verses: 8, type: "meccan", nuzul: 12 },
  { n: 95, en: "At-Tin", ar: "التين", verses: 8, type: "meccan", nuzul: 28 },
  { n: 96, en: "Al-Alaq", ar: "العلق", verses: 19, type: "meccan", nuzul: 1 },
  { n: 97, en: "Al-Qadr", ar: "القدر", verses: 5, type: "meccan", nuzul: 25 },
  { n: 98, en: "Al-Bayyinah", ar: "البينة", verses: 8, type: "medinan", nuzul: 100 },
  { n: 99, en: "Az-Zalzalah", ar: "الزلزلة", verses: 8, type: "medinan", nuzul: 93 },
  { n: 100, en: "Al-Adiyat", ar: "العاديات", verses: 11, type: "meccan", nuzul: 14 },
  { n: 101, en: "Al-Qariah", ar: "القارعة", verses: 11, type: "meccan", nuzul: 30 },
  { n: 102, en: "At-Takathur", ar: "التكاثر", verses: 8, type: "meccan", nuzul: 16 },
  { n: 103, en: "Al-Asr", ar: "العصر", verses: 3, type: "meccan", nuzul: 13 },
  { n: 104, en: "Al-Humazah", ar: "الهمزة", verses: 9, type: "meccan", nuzul: 32 },
  { n: 105, en: "Al-Fil", ar: "الفيل", verses: 5, type: "meccan", nuzul: 19 },
  { n: 106, en: "Quraysh", ar: "قريش", verses: 4, type: "meccan", nuzul: 29 },
  { n: 107, en: "Al-Maun", ar: "الماعون", verses: 7, type: "meccan", nuzul: 17 },
  { n: 108, en: "Al-Kawthar", ar: "الكوثر", verses: 3, type: "meccan", nuzul: 15 },
  { n: 109, en: "Al-Kafirun", ar: "الكافرون", verses: 6, type: "meccan", nuzul: 18 },
  { n: 110, en: "An-Nasr", ar: "النصر", verses: 3, type: "medinan", nuzul: 114 },
  { n: 111, en: "Al-Masad", ar: "المسد", verses: 5, type: "meccan", nuzul: 6 },
  { n: 112, en: "Al-Ikhlas", ar: "الإخلاص", verses: 4, type: "meccan", nuzul: 22 },
  { n: 113, en: "Al-Falaq", ar: "الفلق", verses: 5, type: "meccan", nuzul: 20 },
  { n: 114, en: "An-Nas", ar: "الناس", verses: 6, type: "meccan", nuzul: 21 },
];
